# Generated by Django 4.0.5 on 2022-06-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=50)),
                ('res_room_number', models.IntegerField(max_length=10)),
                ('res_money', models.IntegerField(max_length=10)),
                ('res_type', models.CharField(max_length=5)),
                ('res_ota', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(max_length=5)),
                ('room_type', models.CharField(max_length=10)),
                ('room_floor', models.IntegerField(max_length=3)),
            ],
        ),
    ]
