# Generated by Django 4.0.5 on 2022-06-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohyeah', '0003_totalroomfloor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalroomfloor',
            old_name='room_floor',
            new_name='room_floor_high',
        ),
        migrations.AddField(
            model_name='totalroomfloor',
            name='room_floor_low',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
