# Generated by Django 4.0.5 on 2022-07-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohyeah', '0006_booking_book_room_chkin_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='room',
        ),
    ]
