# Generated by Django 4.0.5 on 2022-07-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohyeah', '0009_alter_reservation_res_ota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='res_chkin_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='res_chkout_date',
            field=models.DateField(null=True),
        ),
    ]
