# Generated by Django 4.0.5 on 2022-07-02 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohyeah', '0010_alter_reservation_res_chkin_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='res_chkin_date',
            new_name='res_chkin',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='res_chkout_date',
            new_name='res_chkout',
        ),
    ]
