# Generated by Django 4.0.5 on 2022-07-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohyeah', '0011_rename_res_chkin_date_reservation_res_chkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='res_modify_date',
            field=models.DateTimeField(null=True),
        ),
    ]
