# Generated by Django 4.0.5 on 2022-07-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohyeah', '0014_alter_booking_book_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_visi',
            field=models.CharField(default='yes', max_length=5),
            preserve_default=False,
        ),
    ]
