# Generated by Django 4.0.5 on 2022-07-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohyeah', '0016_booking_book_status_reservation_res_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='book_number',
            field=models.IntegerField(null=True),
        ),
    ]
