# Generated by Django 4.0.5 on 2022-07-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohyeah', '0019_eventhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='book_night',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='res_night',
            field=models.IntegerField(null=True),
        ),
    ]
