# Generated by Django 4.0.5 on 2022-06-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohyeah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='res_money',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='res_room_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_floor',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=5),
        ),
    ]
