# Generated by Django 4.0.5 on 2022-07-01 16:16

from django.db import migrations, models
from django.utils import timezone
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ohyeah', '0004_rename_room_floor_totalroomfloor_room_floor_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='res_chk_time',
            field=models.TimeField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='res_company',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='res_date',
            field=models.DateTimeField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='res_guest_info',
            field=models.TextField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='res_payment_info',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='res_person',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='res_ota',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='res_room_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_room_number', models.CharField(max_length=5)),
                ('book_room_money', models.CharField(max_length=10)),
                ('book_room_name', models.CharField(max_length=50)),
                ('book_room_guest_type', models.CharField(max_length=10)),
                ('book_room_guest_phone', models.CharField(max_length=10)),
                ('book_room_guest_info', models.TextField()),
                ('book_room_company', models.CharField(max_length=10)),
                ('book_room_person', models.CharField(max_length=3)),
                ('book_room_ota', models.CharField(max_length=10, null=True)),
                ('book_room_payment_info', models.CharField(max_length=50)),
                ('book_room_cancel', models.CharField(max_length=2)),
                ('book_room_chk_time', models.TimeField()),
                ('book_room_date', models.DateTimeField()),
                ('book_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ohyeah.room')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ohyeah.booking'),
            preserve_default=False,
        ),
    ]
