# Generated by Django 4.0.5 on 2022-07-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohyeah', '0007_remove_reservation_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='res_bank_money',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='res_card_money',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='res_cash_money',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='res_guest_phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='res_guest_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='res_misu_money',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='res_money',
            field=models.IntegerField(null=True),
        ),
    ]
