# Generated by Django 4.0.5 on 2022-07-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohyeah', '0008_reservation_res_bank_money_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='res_ota',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
