# Generated by Django 4.0.5 on 2022-07-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohyeah', '0012_reservation_res_modify_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='book_room_chk_time',
            new_name='book_chk_time',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='book_room_company',
            new_name='book_company',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='book_room_chkin_date',
            new_name='book_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='book_room_guest_info',
            new_name='book_guest_info',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='book_room_name',
            new_name='book_guest_phone',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='book_room_guest_phone',
            new_name='book_guest_type',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='book_room_chkout_date',
            new_name='book_modify_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='book_room_payment_info',
            new_name='book_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='book_room_guest_type',
            new_name='book_ota',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='book_room',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='book_room_cancel',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='book_room_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='book_room_money',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='book_room_ota',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='book_room_person',
        ),
        migrations.AddField(
            model_name='booking',
            name='book_bank_money',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='book_card_money',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='book_cash_money',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='book_chkin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='book_chkout',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='book_misu_money',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='book_money',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='book_payment_info',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='book_person',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='book_type',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_room_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
