# Generated by Django 4.0.5 on 2022-07-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohyeah', '0013_rename_book_room_chk_time_booking_book_chk_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='res_company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
