# Generated by Django 4.0.5 on 2022-07-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohyeah', '0015_room_room_visi'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='book_status',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='res_status',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
